ACTION_DO_NOTHING = 'do_nothing'
ACTION_BUILD_SUPPLY_DEPOT = 'build_supply_depot'
ACTION_BUILD_GAS = 'build_gas'
ACTION_BUILD_CC = 'build_cc'
ACTION_BUILD_BARRACKS = 'build_barracks'
ACTION_BUILD_GHOST_ACADEMY = 'build_ghost_academy'
ACTION_BUILD_FACTORY = 'build_factory'
ACTION_BUILD_STARPORT = 'build_starport'
ACTION_BUILD_EBAY = 'build_ebay'
ACTION_BUILD_ARMORY = 'build_armory'
ACTION_BUILD_FUSION_CORE = 'build_fusion_core'
ACTION_BUILD_BUNKER = 'build_bunker'
ACTOIN_BUILD_TURRET = 'build_missle_turret'
ACTOIN_BUILD_SENSOR = 'build_sensor_tower'
ACTION_BUILD_ORBITAL = 'build_orbital'
ACTION_BUILD_PF = 'build_PF'


ACTION_TRAIN_SCV = 'train_scv'
ACTION_TRAIN_MARINE = 'train_marine'

bot_actions = [
ACTION_DO_NOTHING,

# Build Buildings
ACTION_BUILD_SUPPLY_DEPOT,
ACTION_BUILD_GAS,
ACTION_BUILD_CC,
ACTION_BUILD_BARRACKS,
ACTION_BUILD_GHOST_ACADEMY,
ACTION_BUILD_FACTORY,
ACTION_BUILD_STARPORT,
ACTION_BUILD_EBAY,
ACTION_BUILD_ARMORY,
ACTION_BUILD_FUSION_CORE,
ACTION_BUILD_BUNKER,
ACTOIN_BUILD_TURRET,
ACTOIN_BUILD_SENSOR,
ACTION_BUILD_ORBITAL,
ACTION_BUILD_PF,

# Train Units
ACTION_TRAIN_SCV,
ACTION_TRAIN_MARINE,

]
